# Generated by Django 5.0.4 on 2024-04-30 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('method-ARAS', 'ARAS'), ('method-Borda', 'Borda'), ('method-CoCoSo', 'CoCoSo'), ('method-CODAS', 'CODAS'), ('method-Copeland', 'Copeland'), ('method-COPRAS', 'COPRAS'), ('method-CRADIS', 'CRADIS'), ('method-EDAS', 'EDAS'), ('method-GRA', 'GRA'), ('method-MABAC', 'MABAC'), ('method-MACBETH', 'MACBETH'), ('method-MAIRCA', 'MAIRCA'), ('method-MARA', 'MARA'), ('method-MARCOS', 'MARCOS'), ('method-MOORA', 'MOORA'), ('method-MOOSRA', 'MOOSRA'), ('method-OCRA', 'OCRA'), ('method-ORESTE', 'ORESTE'), ('method-PIV', 'PIV'), ('method-PSI', 'PSI'), ('method-REGIME', 'REGIME'), ('method-ROV', 'ROV'), ('method-SAW', 'SAW'), ('method-TODIM', 'TODIM'), ('method-TOPSIS', 'TOPSIS'), ('method-WSM', 'WSM'), ('method-WPM', 'WPM'), ('method-WASPAS', 'WASPAS'), ('method-Simple WISP', 'Simple WISP'), ('method-WISP', 'WISP')], max_length=70)),
                ('hyperparameter', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=30)),
                ('weight', models.FloatField()),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Non_Fuzzy_ranking_methods.method')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Non_Fuzzy_ranking_methods.method')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.ManyToManyField(to='Non_Fuzzy_ranking_methods.choice')),
                ('indicators', models.ManyToManyField(to='Non_Fuzzy_ranking_methods.indicator')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Non_Fuzzy_ranking_methods.method')),
            ],
        ),
        migrations.CreateModel(
            name='MatrixData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Non_Fuzzy_ranking_methods.request')),
            ],
        ),
    ]
