# Generated by Django 5.0.4 on 2024-04-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Non_Fuzzy_ranking_methods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='hyperparameter',
        ),
        migrations.AddField(
            model_name='method',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
