# Generated by Django 5.0.4 on 2024-04-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Non_Fuzzy_ranking_methods', '0002_remove_method_hyperparameter_method_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='hyperparameter_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
